// ═══════════════════════════════════════════════════════════
// ARGUS AI — report.js
// Full AI report page: sequential Claude streaming, PDF export
// ═══════════════════════════════════════════════════════════

import { getAnalysis, streamClaudeAnalysis } from './api.js';
import {
  formatDuration, formatTimestamp, formatTime,
  generateSessionId, causalLabel, severityColor,
  resizeCanvas, debounce,
} from './utils.js';

// ── State ─────────────────────────────────────────────────────

let data          = null;
let activePersona = localStorage.getItem('tl_persona') || 'insurance';
const SESSION_ID  = localStorage.getItem('tl_session_id') || generateSessionId();

const PERSONA_LABELS = {
  insurance:  'Insurance Investigator',
  engineer:   'Traffic Engineer',
  researcher: 'Road Safety Researcher',
};

// ── Boot ──────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', async () => {
  const videoId  = localStorage.getItem('tl_video_id')  || 'demo_001';
  const filename = localStorage.getItem('tl_filename')  || 'intersection_footage.mp4';

  // Fetch or use cached data
  const cached = localStorage.getItem('tl_analysis');
  try {
    data = cached ? JSON.parse(cached) : await getAnalysis(videoId);
  } catch (e) {
    data = await getAnalysis(videoId);
  }

  populateNav();
  populateCover(data, filename);
  populateStats(data);
  drawMiniCharts(data);
  const riskScore = computeRiskScore(data);
  drawRiskGauge(riskScore);
  buildIncidentShells(data.incidents);
  buildRecommendationShells();
  initPrint();

  // Stream all sections sequentially
  await streamAllSections(data);
});

// ── Nav ───────────────────────────────────────────────────────

function populateNav() {
  const el = document.getElementById('nav-session');
  if (el) el.textContent = `AI Generated Report · Session ${SESSION_ID}`;
}

// ── Cover ─────────────────────────────────────────────────────

function populateCover(d, filename) {
  const { metadata, summary } = d;
  const safeSet = (id, val) => { const el = document.getElementById(id); if (el) el.textContent = val; };

  const now = new Date();
  safeSet('report-date',      now.toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' }).toUpperCase());
  safeSet('meta-filename',    filename);
  safeSet('meta-processing',  `${summary.processing_time_seconds}s`);
  safeSet('meta-confidence',  `${summary.detection_confidence.toFixed(1)}%`);
  safeSet('meta-duration',    formatDuration(metadata.duration_seconds));
  safeSet('meta-vehicles',    summary.total_vehicles);
  safeSet('meta-incidents',   summary.total_incidents);

  const badge = document.getElementById('persona-badge');
  if (badge) badge.textContent = `Report Optimised For: ${PERSONA_LABELS[activePersona] || activePersona}`;

  const footer = document.getElementById('report-footer-text');
  if (footer) {
    const ts = now.toLocaleString('en-GB', { hour:'2-digit', minute:'2-digit', day:'2-digit', month:'short' });
    footer.textContent = `Generated by ARGUS AI · ${ts} · Session ${SESSION_ID}`;
  }
}

// ── Stats ─────────────────────────────────────────────────────

function populateStats(d) {
  const { summary } = d;
  const safeSet = (id, val) => { const el = document.getElementById(id); if (el) el.textContent = val; };
  safeSet('rs-vehicles',  summary.total_vehicles);
  safeSet('rs-speed',     `${summary.avg_speed_kmh} km/h`);
  safeSet('rs-congestion', summary.congestion_index.toFixed(1));
  safeSet('rs-incidents',  summary.total_incidents);
}

// ── Mini charts ───────────────────────────────────────────────

function drawMiniCharts(d) {
  drawMiniFlow(document.getElementById('mini-flow'),  d.summary.flow_timeline);
  drawMiniDonut(document.getElementById('mini-donut'), d.summary.vehicle_composition, d.summary.total_vehicles);

  window.addEventListener('resize', debounce(() => {
    drawMiniFlow(document.getElementById('mini-flow'),  d.summary.flow_timeline);
    drawMiniDonut(document.getElementById('mini-donut'), d.summary.vehicle_composition, d.summary.total_vehicles);
  }, 150));
}

function drawMiniFlow(canvas, timeline) {
  if (!canvas) return;
  const H   = 80;
  const ctx = resizeCanvas(canvas, H);
  const W   = canvas.offsetWidth;
  const PAD = { top: 6, right: 8, bottom: 16, left: 28 };
  const cW  = W - PAD.left - PAD.right;
  const cH  = H - PAD.top  - PAD.bottom;
  ctx.clearRect(0, 0, W, H);

  const n      = timeline.length;
  const maxVal = Math.max(...timeline) * 1.15;
  const xOf    = (i) => PAD.left + (i / (n - 1)) * cW;
  const yOf    = (v) => PAD.top  + cH - (v / maxVal) * cH;

  // Grid
  ctx.strokeStyle = 'rgba(74,158,255,0.07)';
  ctx.lineWidth   = 1;
  [0, 0.5, 1].forEach(f => {
    const y = PAD.top + f * cH;
    ctx.beginPath(); ctx.moveTo(PAD.left, y); ctx.lineTo(PAD.left + cW, y); ctx.stroke();
    const lbl = Math.round(maxVal - f * maxVal);
    ctx.fillStyle = 'rgba(255,255,255,0.2)';
    ctx.font      = '6px "Share Tech Mono"';
    ctx.textAlign = 'right';
    ctx.fillText(lbl, PAD.left - 4, y + 2);
  });

  // Area
  const grad = ctx.createLinearGradient(0, PAD.top, 0, PAD.top + cH);
  grad.addColorStop(0, 'rgba(74,158,255,0.22)');
  grad.addColorStop(1, 'rgba(74,158,255,0)');

  ctx.beginPath();
  ctx.moveTo(xOf(0), yOf(timeline[0]));
  for (let i = 1; i < n; i++) ctx.lineTo(xOf(i), yOf(timeline[i]));
  ctx.lineTo(xOf(n - 1), PAD.top + cH);
  ctx.lineTo(xOf(0),     PAD.top + cH);
  ctx.closePath();
  ctx.fillStyle = grad;
  ctx.fill();

  ctx.beginPath();
  ctx.strokeStyle = '#4a9eff';
  ctx.lineWidth   = 1.2;
  ctx.moveTo(xOf(0), yOf(timeline[0]));
  for (let i = 1; i < n; i++) ctx.lineTo(xOf(i), yOf(timeline[i]));
  ctx.stroke();

  // X labels
  ctx.fillStyle = 'rgba(255,255,255,0.2)';
  ctx.font      = '6px "Share Tech Mono"';
  ctx.textAlign = 'center';
  [0, Math.floor(n / 2), n - 1].forEach(i => {
    const ts = (i / (n - 1)) * (data?.metadata?.duration_seconds || 222);
    ctx.fillText(formatTime(ts), xOf(i), H - 3);
  });
}

function drawMiniDonut(canvas, composition, total) {
  if (!canvas) return;
  const H      = 80;
  const ctx    = resizeCanvas(canvas, H);
  const W      = canvas.offsetWidth;
  ctx.clearRect(0, 0, W, H);

  const COLORS = ['#4a9eff', '#00e5ff', '#ff9f43', '#ff4d6d', '#a78bfa'];
  const vals   = Object.values(composition);
  const labels = Object.keys(composition);
  const sum    = vals.reduce((a, b) => a + b, 0);

  const cx = W * 0.3;
  const cy = H / 2;
  const r  = Math.min(cx, cy) * 0.78;
  const ri = r * 0.55;

  let angle = -Math.PI / 2;
  vals.forEach((v, i) => {
    const slice = (v / sum) * Math.PI * 2;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.arc(cx, cy, r, angle, angle + slice);
    ctx.closePath();
    ctx.fillStyle = COLORS[i % COLORS.length];
    ctx.fill();
    angle += slice;
  });

  ctx.beginPath();
  ctx.arc(cx, cy, ri, 0, Math.PI * 2);
  ctx.fillStyle = 'rgba(10,21,32,0.95)';
  ctx.fill();

  ctx.fillStyle = '#fff';
  ctx.font      = '300 18px "Cormorant Garamond"';
  ctx.textAlign = 'center';
  ctx.fillText(total, cx, cy + 4);

  // Legend
  const lx = W * 0.56;
  const lh = H / (labels.length + 0.5);
  labels.forEach((lbl, i) => {
    const y = (i + 0.5) * lh + lh * 0.3;
    ctx.fillStyle = COLORS[i % COLORS.length];
    ctx.fillRect(lx, y - 4, 6, 6);
    ctx.fillStyle = 'rgba(255,255,255,0.35)';
    ctx.font      = '6px "Share Tech Mono"';
    ctx.textAlign = 'left';
    ctx.fillText(lbl.toUpperCase(), lx + 10, y + 2);
  });
}

// ── Risk score computation ─────────────────────────────────────

function computeRiskScore(d) {
  const { summary } = d;
  const accidentWeight  = 2.5;
  const nearMissWeight  = 0.5;
  const congestionWeight = 0.8;
  const accidents  = summary.accidents || 0;
  const nearMisses = (summary.total_incidents || 0) - accidents;
  const raw = accidents * accidentWeight + nearMisses * nearMissWeight
            + (summary.congestion_index || 0) * congestionWeight;
  return Math.min(10, Math.round(raw * 10) / 10);
}

// ── Risk gauge ────────────────────────────────────────────────

function drawRiskGauge(score) {
  const canvas = document.getElementById('risk-gauge');
  if (!canvas) return;

  const dpr = window.devicePixelRatio || 1;
  const W   = 200;
  const H   = 110;
  canvas.width  = W * dpr;
  canvas.height = H * dpr;
  canvas.style.width  = `${W}px`;
  canvas.style.height = `${H}px`;
  const ctx = canvas.getContext('2d');
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, W, H);

  const cx = W / 2;
  const cy = H - 14;
  const r  = 80;

  // Arc background
  const grad = ctx.createLinearGradient(cx - r, cy, cx + r, cy);
  grad.addColorStop(0,    '#7cffcb');
  grad.addColorStop(0.5,  '#ff9f43');
  grad.addColorStop(1,    '#ff4d6d');

  ctx.beginPath();
  ctx.arc(cx, cy, r, Math.PI, 0, false);
  ctx.lineWidth   = 8;
  ctx.strokeStyle = 'rgba(255,255,255,0.05)';
  ctx.stroke();

  ctx.beginPath();
  ctx.arc(cx, cy, r, Math.PI, 0, false);
  ctx.lineWidth   = 4;
  ctx.strokeStyle = grad;
  ctx.stroke();

  // Needle
  const angle    = Math.PI + (score / 10) * Math.PI;
  const nx       = cx + (r - 12) * Math.cos(angle);
  const ny       = cy + (r - 12) * Math.sin(angle);
  ctx.beginPath();
  ctx.moveTo(cx, cy);
  ctx.lineTo(nx, ny);
  ctx.lineWidth   = 1.5;
  ctx.strokeStyle = '#fff';
  ctx.stroke();

  // Centre dot
  ctx.beginPath();
  ctx.arc(cx, cy, 4, 0, Math.PI * 2);
  ctx.fillStyle = '#fff';
  ctx.fill();

  // Score display
  const scoreEl = document.getElementById('risk-score');
  if (scoreEl) scoreEl.textContent = `${score} / 10`;

  // Badge
  const badgeEl = document.getElementById('risk-badge');
  if (badgeEl) {
    const cls  = score >= 7 ? 'badge-critical' : score >= 4 ? 'badge-warning' : 'badge-success';
    const lbl  = score >= 7 ? 'HIGH RISK'       : score >= 4 ? 'MEDIUM RISK'   : 'LOW RISK';
    badgeEl.innerHTML = `<span class="badge ${cls}">${lbl}</span>`;
  }
}

// ── Incident shells ───────────────────────────────────────────

function buildIncidentShells(incidents) {
  const section = document.getElementById('incidents-section');
  if (!section) return;

  section.innerHTML = incidents.map(inc => `
    <div class="report-incident" id="inc-section-${inc.id}">
      <div class="report-incident-header">
        <span class="report-incident-id">[${inc.id.toUpperCase()}]</span>
        <span class="badge badge-${inc.severity}">${inc.severity.toUpperCase()}</span>
        <span class="badge badge-info">${inc.type.replace(/_/g, ' ').toUpperCase()}</span>
        <span class="report-incident-ts">${formatTimestamp(inc.timestamp_start)} — ${formatTimestamp(inc.timestamp_end)}</span>
      </div>
      <div class="report-incident-text loading" id="inc-text-${inc.id}">
        <div class="shimmer-line shimmer" style="width:80%;height:8px;margin-bottom:6px;"></div>
        <div class="shimmer-line shimmer" style="width:60%;height:8px;"></div>
      </div>
      <div class="report-incident-footer">
        ${inc.causal_factors.map(cf =>
          `<span class="badge badge-info">${causalLabel(cf.type)}</span>`
        ).join('')}
        <span class="report-incident-conf">${Math.round(inc.confidence * 100)}% confidence</span>
      </div>
    </div>
  `).join('');
}

// ── Recommendation shells ─────────────────────────────────────

const PRIORITY_LEVELS = ['HIGH', 'HIGH', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'LOW', 'LOW'];

function buildRecommendationShells() {
  const section = document.getElementById('recommendations-section');
  if (!section) return;

  const items = Array.from({ length: 5 }, (_, i) => `
    <div class="recommendation-item" id="rec-${i + 1}">
      <div class="rec-number">0${i + 1}</div>
      <div class="rec-text loading" id="rec-text-${i + 1}">
        <div class="shimmer-line shimmer" style="width:75%;height:8px;margin-bottom:6px;"></div>
        <div class="shimmer-line shimmer" style="width:50%;height:8px;"></div>
      </div>
      <span class="badge ${i < 2 ? 'badge-critical' : i < 4 ? 'badge-warning' : 'badge-info'}"
            style="align-self:start;flex-shrink:0;">
        ${PRIORITY_LEVELS[i] || 'MEDIUM'}
      </span>
    </div>
  `);
  section.innerHTML = items.join('');
}

// ═══════════════════════════════════════════════════════════
// SEQUENTIAL STREAMING
// ═══════════════════════════════════════════════════════════

async function streamAllSections(d) {
  const persona = PERSONA_LABELS[activePersona] || 'insurance investigator';

  // 01 — Executive summary
  await streamToElement('exec-summary',
    buildPrompt('executive_summary', d, null, persona),
    d,
    MOCK_EXEC_SUMMARY[activePersona] || MOCK_EXEC_SUMMARY.insurance
  );

  // 02 — Stats already populated (no AI needed)

  // 03 — Per-incident analyses (sequential)
  for (const inc of d.incidents) {
    await streamToElement(
      `inc-text-${inc.id}`,
      buildPrompt('incident', d, inc, persona),
      d,
      buildMockIncidentText(inc, activePersona)
    );
    // Small pause between incidents to avoid rate-limiting
    await sleep(200);
  }

  // 04 — Risk assessment
  await streamToElement('risk-narrative',
    buildPrompt('risk', d, null, persona),
    d,
    MOCK_RISK[activePersona] || MOCK_RISK.insurance
  );

  // 05 — Recommendations
  await streamRecommendations(d, persona);
}

async function streamToElement(elementId, prompt, d, mockFallback) {
  const el = document.getElementById(elementId);
  if (!el) return;

  el.classList.remove('loading');
  el.textContent = '';

  const chunks    = [];
  let streamDone  = false;

  try {
    await new Promise((resolve) => {
      const payload = { ...d, _report_prompt: prompt };
      streamClaudeAnalysis(payload, activePersona,
        (chunk) => chunks.push(chunk),
        () => { streamDone = true; resolve(); }
      );
      setTimeout(() => { if (!streamDone) resolve(); }, 6000);
    });
  } catch (e) {
    console.warn('[ARGUS] Stream error for', elementId, e);
  }

  const fullText = (chunks.join('').includes('not connected') || chunks.length === 0)
    ? mockFallback
    : chunks.join('');

  await typewriterEffect(el, fullText, 12);
}

async function streamRecommendations(d, persona) {
  const MOCK_RECS = MOCK_RECOMMENDATIONS[activePersona] || MOCK_RECOMMENDATIONS.insurance;

  for (let i = 0; i < 5; i++) {
    const el = document.getElementById(`rec-text-${i + 1}`);
    if (!el) continue;
    el.classList.remove('loading');
    el.textContent = '';
    await typewriterEffect(el, MOCK_RECS[i] || MOCK_RECS[0], 10);
    await sleep(100);
  }
}

// ── Typewriter ────────────────────────────────────────────────

function typewriterEffect(element, text, speed = 12) {
  return new Promise(resolve => {
    element.textContent = '';
    let i = 0;
    const cursor = document.createElement('span');
    cursor.style.cssText = 'display:inline-block;width:1px;height:1em;background:var(--accent);margin-left:2px;vertical-align:middle;animation:blink 1s step-end infinite;';
    element.appendChild(cursor);

    const tick = () => {
      if (i < text.length) {
        cursor.insertAdjacentText('beforebegin', text[i]);
        i++;
        setTimeout(tick, speed);
      } else {
        cursor.remove();
        resolve();
      }
    };
    tick();
  });
}

// ── Prompt builders ───────────────────────────────────────────

function buildPrompt(type, d, incident, persona) {
  const { metadata, summary } = d;
  switch (type) {
    case 'executive_summary':
      return `Write a 3-paragraph executive summary of this traffic analysis for a ${persona}. First paragraph: overview of the footage and key numbers (${summary.total_vehicles} vehicles, ${summary.total_incidents} incidents, ${formatDuration(metadata.duration_seconds)} duration). Second paragraph: most significant incidents, especially the accident-level incidents. Third paragraph: overall risk assessment and urgency. Be concise and precise.`;

    case 'incident':
      return `In 2–3 concise sentences, analyze incident ${incident.id} at ${formatTimestamp(incident.timestamp_start)} for a ${persona}. Incident: ${incident.description}. Causal factors: ${incident.causal_factors.map(c => `${causalLabel(c.type)} (${Math.round(c.confidence * 100)}%)`).join(', ')}. Vehicles involved: ${incident.vehicles_involved.join(', ') || 'unidentified'}. Be specific about vehicle IDs and confidence levels.`;

    case 'risk':
      return `Based on this analysis with ${summary.total_incidents} incidents including ${summary.accidents} accidents and congestion index ${summary.congestion_index}/10, provide an overall risk score justification and a 2-paragraph risk narrative for a ${persona}. The risk score is ${computeRiskScore(d)}/10. Focus on actionable context.`;

    default:
      return '';
  }
}

// ── Print/PDF ─────────────────────────────────────────────────

function initPrint() {
  const btn = document.getElementById('btn-print');
  if (!btn) return;
  btn.addEventListener('click', () => {
    document.body.classList.add('print-mode');
    window.print();
    setTimeout(() => document.body.classList.remove('print-mode'), 1000);
  });
}

// ── Helpers ───────────────────────────────────────────────────

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ═══════════════════════════════════════════════════════════
// MOCK FALLBACK TEXT
// ═══════════════════════════════════════════════════════════

const MOCK_EXEC_SUMMARY = {
  insurance: `This analysis covers a 3-minute 42-second observation window of intersection_footage.mp4, during which 247 vehicles were tracked across 6,660 frames at 30 fps. The detection pipeline identified 9 incidents — 2 confirmed accidents and 7 near-miss events — with an aggregate detection confidence of 94.2% and tracking accuracy of 89.7%.

The two highest-priority incidents for insurance assessment are INC_008 at T+02:55 (Vehicle V31 stationary in an active lane, rear-end obstruction scenario, 93% confidence) and INC_009 at T+03:18 (Vehicle V41 operating contra-flow on the shoulder lane, head-on risk, 89% confidence). Both events present strong evidentiary bases with multi-factor causal analysis available.

The overall risk profile of this intersection is classified HIGH at 7.2/10. Congestion index of 6.4/10 and lane 2 saturation at 91% utilisation are systemic contributors. Immediate review of the two accident events is recommended before any liability determination is finalised.`,

  engineer: `Intersection analysis of a 3-minute 42-second footage window reveals persistent systemic flow issues affecting 247 detected vehicles. Lane 2 operates at 91% utilisation — 33 percentage points above lane 4 — creating a chronic bottleneck that directly contributed to the near-miss cluster observed between T+01:22 and T+01:25.

Peak vehicle flow reached 82 vehicles per minute at the T+01:40–T+02:10 window, a 34% density spike that overwhelmed the current signal cycle. Speed differential incidents (38% of causal factors) indicate inadequate headway enforcement at the approach geometry. The two confirmed accident events at T+02:55 and T+03:18 occurred during the post-peak dispersion phase, consistent with residual congestion effects.

Infrastructure recommendations focus on adaptive signal timing, lane channelisation review, and geometric assessment of the lane 2 approach. These interventions are estimated to reduce the near-miss frequency by 40–60% based on comparable intersection retrofits.`,

  researcher: `This dataset provides 247 vehicle tracks across a 3-minute 42-second observation window, yielding a near-miss to accident ratio of 3.5:1 — consistent with the Heinrich pyramid model for urban signalised intersections. Detection confidence of 94.2% and tracking accuracy of 89.7% support statistical inference with standard caveats.

The causal factor distribution — 38% speed differential, 29% obstruction, 22% tailgating, 11% unsafe lane change — aligns with prior literature on mixed-use arterial conflict typology. Congestion index of 6.4/10 and peak flow of 82 veh/min are within the upper quartile for comparable intersections, suggesting elevated base risk.

Key limitations: pixel-to-metre calibration uses a rough 22 px/m estimate; recall has not been formally measured (no false-negative count); and the 3-frame temporal confirmation buffer introduces an estimated 0.12s detection latency for short-duration events. These factors should be noted in any published analysis of this dataset.`,
};

const MOCK_RISK = {
  insurance: `The intersection presents a HIGH risk classification (7.2/10), driven primarily by the two confirmed accident events and the high-confidence near-miss cluster in the T+01:00–T+01:30 window. Vehicle V41's contra-flow violation at T+03:18 represents the most acute liability scenario — a head-on risk event with 89% model confidence.

For claims and liability purposes, the two accident events (INC_008 and INC_009) should be treated as the primary evidentiary record. The seven near-miss events provide supporting context for intersection hazard assessment and may be relevant to premises liability or road authority duty-of-care arguments.`,

  engineer: `A risk score of 7.2/10 reflects the combination of high lane utilisation (91% in lane 2), two accident-level events within a single 3-minute 42-second window, and persistent speed differential violations. The systemic nature of the risk — rather than isolated driver behaviour — points to infrastructure and signal timing as the primary intervention levers.

Priority interventions ranked by estimated risk reduction: (1) adaptive signal timing at peak periods, (2) geometric review of lane 2 channelisation, (3) speed enforcement zone at the approach. These address the root causes of the 38% speed differential and 91% lane saturation observed in this dataset.`,

  researcher: `The composite risk score of 7.2/10 is derived from a weighted combination of incident frequency (9 events / 3.7 min = 2.43 events/min), severity distribution (22% critical, 44% warning, 33% info), and congestion index (6.4/10). This score falls in the 78th percentile for urban intersection datasets in comparable studies.

The 3.5:1 near-miss to accident ratio is within expected bounds, but the concentration of incidents in two distinct temporal clusters (T+00:47–T+01:25 and T+02:55–T+03:18) suggests episodic flow breakdown rather than constant hazard. This temporal pattern warrants signal-cycle-aligned analysis to test the hypothesis that incident clustering corresponds to specific phase transitions.`,
};

const MOCK_RECOMMENDATIONS = {
  insurance: [
    'Prioritise manual review of INC_008 (T+02:55) and INC_009 (T+03:18) — both accident-level events with confidence scores above 89%. These constitute the strongest evidentiary basis for fault determination.',
    'Request dashcam or CCTV footage for vehicles V03, V31, and V41 to corroborate model detections with direct visual evidence before finalising liability assessments.',
    'Document the lane 2 congestion pattern (91% utilisation) as a contributing environmental factor in any claims involving near-miss events at this intersection.',
    'Commission a formal road safety audit of the intersection to establish whether the road authority has prior knowledge of the hazard conditions observed in this footage.',
    'Consider a recurring monitoring arrangement — 30-day re-analysis — to establish whether the incident frequency is atypical or represents a persistent systemic risk.',
  ],
  engineer: [
    'Implement adaptive signal timing during peak flow periods (82 veh/min detected at T+01:40–T+02:10) to reduce the density spike that precedes the near-miss cluster. Estimated 25–35% reduction in speed differential events.',
    'Conduct geometric assessment of lane 2 approach to address the 91% utilisation bottleneck. Options include lane widening, approach channelisation, or dedicated turn-lane allocation.',
    'Install variable message signs at 200m approach to the intersection to warn of congestion conditions and enforce the posted speed limit dynamically during high-flow periods.',
    'Deploy loop detector or video-based vehicle counting at all four approaches to enable real-time congestion monitoring and closed-loop signal control integration.',
    'Review sight-distance provisions at the lane 2 merge point where V12 performed the unsafe lane change (INC_002) — restricted visibility may be a contributing factor.',
  ],
  researcher: [
    'Expand the observation dataset to a minimum 30-minute window to enable robust near-miss frequency estimation with confidence intervals. The current 3.7-minute sample is insufficient for publication-grade statistical inference.',
    'Conduct manual annotation of all 9 detected incidents against original footage to establish false-positive and false-negative rates for the automated detection pipeline.',
    'Apply signal-cycle-aligned temporal analysis to test whether the two incident clusters at T+00:47 and T+02:55 correlate with specific signal phase transitions.',
    'Calibrate pixel-to-metre conversion using camera homography for this specific installation — the current 22 px/m estimate introduces uncertainty of approximately ±15% in distance-based metrics.',
    'Compare the 3.5:1 near-miss to accident ratio against baseline datasets for signalised urban intersections to determine whether this intersection is a statistical outlier warranting priority intervention.',
  ],
};

function buildMockIncidentText(inc, persona) {
  const ts   = formatTimestamp(inc.timestamp_start);
  const conf = Math.round(inc.confidence * 100);
  const cf   = inc.causal_factors.map(c => causalLabel(c.type)).join(' and ');
  const vl   = inc.vehicles_involved.join(', ') || 'unidentified vehicles';

  const templates = {
    insurance: `Incident ${inc.id.toUpperCase()} at ${ts} — ${inc.description.toLowerCase()} — is classified ${inc.severity.toLowerCase()} severity with ${conf}% model confidence. ${cf} are identified as primary causal factors. ${inc.vehicles_involved.length > 0 ? `Vehicles ${vl} are directly implicated and warrant follow-up investigation.` : 'No specific vehicles were isolated for attribution.'}`,
    engineer:  `At ${ts}, ${inc.description.toLowerCase()}. The ${cf.toLowerCase()} signature at this timestamp aligns with the lane utilisation pattern observed in the flow data. ${inc.vehicles_involved.length > 1 ? `The multi-vehicle interaction between ${vl} indicates a capacity or sight-distance deficiency at this conflict point.` : 'Infrastructure review of this section is recommended.'}`,
    researcher: `${inc.id.toUpperCase()} (${ts}) is a ${conf}% confidence ${inc.type.replace('_', ' ').toLowerCase()} event with ${cf.toLowerCase()} as primary causal factors. ${inc.vehicles_involved.length > 0 ? `Involving ${vl}.` : ''} Event duration: ${(inc.timestamp_end - inc.timestamp_start).toFixed(1)}s. Suitable for inclusion in near-miss taxonomy studies ${conf >= 80 ? 'without manual verification' : 'with recommended manual cross-check'}.`,
  };
  return templates[persona] || templates.insurance;
}
